services:

  mysql:
    image: mysql:8.0
    container_name: hotel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hotel_management
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: hotel-backend:latest
    container_name: hotel-backend
    ports:
      - "8081:8081"
    depends_on:
      - mysql

volumes:
  mysql_data: